<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Hotel;

class HotelsTableSeeder extends Seeder
{
    public function run()
    {
        $hotels = [
            [
                'nama' => 'DE COZY INN MOJOKERTO',
                'harga' => 204000,
                'rating' => 4.1,
                'hotel_image_url' => 'DE_COZY_INN_MOJOKERTO.jpeg',
                'lokasi' => 'Dsn Pasinan, Jl. Mangga I, Jabon, Mojoanyar, Mojokerto Regency, East Java 61364',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Sarapan','Parkir','AC/Pemanas','Playground','Lobby Hotel','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Akses ke Layanan Tambahan','Fleksibilitas Reservasi','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Mojokerto Classic Homestay',
                'harga' => 198000,
                'rating' => 3.8,
                'hotel_image_url' => 'Mojokerto_Classic_Homestay.jpg',
                'lokasi' => 'Jl. Jayanegara No.59, Jetis, Banjaragung, Kec. Puri, Kabupaten Mojokerto, Jawa Timur 61363',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Parkir','AC/Pemanas','Lobby Hotel','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Informasi','Pelatihan Staf','Fleksibilitas Reservasi','Keamanan Aksesibilitas'],
            ],
            [
                'nama' => 'Gadjah Mada Hall Cafe & Penginapan Hostel',
                'harga' => 68265,
                'rating' => 3.8,
                'hotel_image_url' => 'gadjah_mada_hall_cafe_&_penginapan_hostel.jpg',
                'lokasi' => 'Jl. Koperasi Ledok, Pacet, Kec. Pacet, Kabupaten Mojokerto, Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Parkir','Playground','Lobby Hotel','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi'],
            ],
            [
                'nama' => 'Grand Whiz Hotel Trawas Mojokerto',
                'harga' => 212493,
                'rating' => 4.4,
                'hotel_image_url' => 'Grand_Whiz_Hotel_Trawas_Mojokerto.jpg',
                'lokasi' => 'Jl. Raya Trawas Jibru, Belik, Kec. Trawas, Kabupaten Mojokerto, Jawa Timur 61375',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Sarapan','Parkir','AC/Pemanas','Playground','Lobby Hotel','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Akses ke Layanan Tambahan','Fleksibilitas Reservasi','Kerjasama Organisasi dan Asosiasi'],
            ],
            [
                'nama' => 'Hotel Surya Kertajaya',
                'harga' => 165750,
                'rating' => 3.9,
                'hotel_image_url' => 'Hotel_Surya_Kertajaya.jpg',
                'lokasi' => 'Jl. By Pass Mojokerto No.KM. 50, Mergelo, Meri, Kec. Magersari, Kota Mojokerto, Jawa Timur 61315',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Sarapan','Parkir','AC/Pemanas','Playground','Lobby Hotel','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Keamanan Aksesibilitas','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Hotel Tejo Wulan',
                'harga' => 75000,
                'rating' => 2.9,
                'hotel_image_url' => 'Hotel_Tejo_Wulan.jpg',
                'lokasi' => 'Jl. Raya Jabon No.2 Jokodayo Jabon Mojokerto Jawa Timur 61364',
                'fasilitas' => ['Kamar','Parkir','AC/Pemanas'],
                'kualitas_layanan' => ['Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Keamanan Aksesibilitas'],
            ],
            [
                'nama' => 'Welirang Resort Pacet',
                'harga' => 247394,
                'rating' => 3.3,
                'hotel_image_url' => 'Welirang_Resort_Pacet.jpg',
                'lokasi' => '8G8X+GQJ Hutan Kec. Pacet Kabupaten Mojokerto Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Sarapan','Parkir','Lobby Hotel','Televisi'],
                'kualitas_layanan' => ['Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Keamanan Aksesibilitas'],
            ],
            [
                'nama' => 'Salmas Guesthouse',
                'harga' => 187535,
                'rating' => 4.2,
                'hotel_image_url' => 'Salmas_Guesthouse.jpg',
                'lokasi' => 'Jl. By Pass Mojokerto No.50 Mergelo Meri Kec. Magersari Kota Mojokerto Jawa Timur 61315',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','Lobby Hotel','Ruangan Fungsional'],
                'kualitas_layanan' => ['Keramahan Staf','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Kerjasama Organisasi dan Asosiasi'],
            ],
            [
                'nama' => 'Naga Mas Losmen',
                'harga' => 185000,
                'rating' => 4,
                'hotel_image_url' => 'Naga_Mas_Losmen.jpg',
                'lokasi' => 'Jl. Pahlawan No.23 Mergelo Kranggan Kec. Prajurit Kulon Kota Mojokerto Jawa Timur 61321',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Parkir','AC/Pemanas','Lobby Hotel','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Pelatihan Staf','Fleksibilitas Reservasi','Keamanan Aksesibilitas','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'HOTEL BUKIT SURYA',
                'harga' => 195000,
                'rating' => 4.2,
                'hotel_image_url' => 'HOTEL_BUKIT_SURYA.jpg',
                'lokasi' => 'Jl. Air Panas No.4 Padusan Kec. Pacet Kabupaten Mojokerto Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Sarapan','Parkir','AC/Pemanas','Playground','Lobby Hotel','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Akses ke Layanan Tambahan','Fleksibilitas Reservasi','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Dmadinah Residence Mojokerto (Syariah)',
                'harga' => 150000,
                'rating' => 4.5,
                'hotel_image_url' => 'Dmadinah_Residence_Mojokerto.jpg',
                'lokasi' => 'Jl. Mangga 1, Dsn Pasinan, Pasiman Jabon, Kec. Mojoanyar, Kabupaten Mojokerto, Jawa Timur 61318',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','AC/Pemanas','Lobby Hotel','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Kebersihan dan Perawatan Kamar','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Pelatihan Staf','Keamanan Aksesibilitas','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Hotel Asri',
                'harga' => 135000,
                'rating' => 3.6,
                'hotel_image_url' => 'Hotel_Asri.jpg',
                'lokasi' => 'GFF4+6J4, Jl. Raya By Pass, Mergelo, Gn. Gedangan, Kec. Magersari, Kota Mojokerto, Jawa Timur 61315',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir'],
                'kualitas_layanan' => ['Keramahan Staf','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik'],
            ],
            [
                'nama' => 'Ecolodge Seloliman',
                'harga' => 255000,
                'rating' => 4.6,
                'hotel_image_url' => 'Ecolodge_Seloliman.jpg',
                'lokasi' => 'Seloliman, Dusun Biting, Seloliman, RT.01/RW.01, Seloliman, Mojokerto Regency, East Java 61375',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Sarapan','Parkir','AC/Pemanas','Playground','Lobby Hotel','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Akses ke Layanan Tambahan','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Hotel Mulya Jaya',
                'harga' => 200000,
                'rating' => 3.6,
                'hotel_image_url' => 'Hotel_Mulya_Jaya.jpg',
                'lokasi' => 'Jl. Raya Penanggalan No.489, Dimoro, Penanggalan Dimoro, Dukuhdimoro, Kec. Mojoagung, Kabupaten Jombang, Jawa Timur 61482',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','Lobby Hotel','Televisi'],
                'kualitas_layanan' => ['Personalisasi Layanan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik'],
            ],
            [
                'nama' => 'DeResort Hotel',
                'harga' => 255000,
                'rating' => 4.3,
                'hotel_image_url' => 'DeResort_Hotel.jpg',
                'lokasi' => 'Jl. Raya By Pass KM.48, Mergelo, Gn. Gedangan, Kec. Magersari, Kota Mojokerto, Jawa Timur 61315',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Sarapan','Parkir','AC/Pemanas','Lobby Hotel','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Akses ke Layanan Tambahan','Fleksibilitas Reservasi','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Penginapan PASUNDAN',
                'harga' => 506000,
                'rating' => 4.4,
                'hotel_image_url' => 'Penginapan_PASUNDAN.jpg',
                'lokasi' => 'Ponpes Amanatul Ummah, Jln. Tirtowening KM.06, Dsn Paras, 300M Sebelah Utara Kembang, Kembangbelor, Kec. Pacet, Kabupaten Mojokerto, Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Parkir','AC/Pemanas','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses ke Layanan Tambahan','Fleksibilitas Reservasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Bobocabin Pacet Mojokerto',
                'harga' => 580000,
                'rating' => 4.7,
                'hotel_image_url' => 'Bobocabin_Pacet_Mojokerto.jpg',
                'lokasi' => '8G8X+GQJ, Hutan, Kec. Pacet, Kabupaten Mojokerto, Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Parkir','Playground','Lobby Hotel','Ruangan Fungsional'],
                'kualitas_layanan' => ['Keramahan Staf','Kebersihan dan Perawatan Kamar','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Akses ke Layanan Tambahan','Fleksibilitas Reservasi','Keamanan Aksesibilitas','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Hotel Tenera',
                'harga' => 142500,
                'rating' => 4.2,
                'hotel_image_url' => 'Hotel_Tenera.jpg',
                'lokasi' => 'Jl. HOS. Cokro Aminoto No.3, Mergelo, Jagalan, Kec. Magersari, Kota Mojokerto, Jawa Timur 61300',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Parkir','AC/Pemanas','Lobby Hotel','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Keamanan Aksesibilitas','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Puri Srijaya Hotel',
                'harga' => 400000,
                'rating' => 3.9,
                'hotel_image_url' => 'Puri_Srijaya_Hotel.jpg',
                'lokasi' => 'Jl. Ahmad Yani No.141, Made, Pacet, Kec. Pacet, Kabupaten Mojokerto, Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','Lobby Hotel','Ruangan Fungsional'],
                'kualitas_layanan' => ['Kebersihan dan Perawatan Kamar','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Pelatihan Staf','Akses ke Layanan Tambahan','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Carina Hotel',
                'harga' => 150000,
                'rating' => 3.8,
                'hotel_image_url' => 'Carina_Hotel.jpg',
                'lokasi' => 'Padusan, Kec. Pacet, Kabupaten Mojokerto, Jawa Timur',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','Lobby Hotel','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Kebersihan dan Perawatan Kamar','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Fleksibilitas Reservasi','Keamanan Aksesibilitas','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Hotel Permata Biru',
                'harga' => 400000,
                'rating' => 4.2,
                'hotel_image_url' => 'Hotel_Permata_Biru.jpg',
                'lokasi' => 'Jalan Raya Terawas No. 21 Dusun Sumberwekas Lumbang Rejo Prigen Sumber Wekas Lumbangrejo Kec. Prigen Pasuruan Jawa Timur 67157',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Parkir','Playground','Lobby Hotel','Ruangan Fungsional'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Pelatihan Staf','Akses ke Layanan Tambahan','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Villa Kamaran Pacet',
                'harga' => 70000,
                'rating' => 4.1,
                'hotel_image_url' => 'Villa_Kamaran_Pacet.jpg',
                'lokasi' => 'Jl. Air Panas No.25 Padusan Kec. Pacet Kabupaten Mojokerto Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Parkir','Televisi'],
                'kualitas_layanan' => ['Kebersihan dan Perawatan Kamar','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Avila Ketapan Rame Hotel',
                'harga' => 321480,
                'rating' => 4.3,
                'hotel_image_url' => 'Avila_Ketapan_Rame_Hotel.jpg',
                'lokasi' => 'Jl. Raya Tretes - Trawas No.78 Slepi Ketapanrame Kec. Trawas Kabupaten Mojokerto Jawa Timur 61375',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Sarapan','Parkir','AC/Pemanas','Playground','Lobby Hotel','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Akses ke Layanan Tambahan','Fleksibilitas Reservasi','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Hotel Newstart',
                'harga' => 250000,
                'rating' => 4.2,
                'hotel_image_url' => 'Hotel_Newstart.jpg',
                'lokasi' => 'Jalan Raya Trawas Dusun Slepi Desa Ketapan Rame RT.2/RW.1 Njuwok Ketapanrame Kec. Trawas Kabupaten Mojokerto Jawa Timur 61375',
                'fasilitas' => ['Kamar','Kamar Mandi','Sarapan','Parkir','Playground','Lobby Hotel','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Pelatihan Staf','Akses ke Layanan Tambahan','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Griya Amin Mojokerto',
                'harga' => 210000,
                'rating' => 3.9,
                'hotel_image_url' => 'Griya_Amin_Mojokerto.jpg',
                'lokasi' => 'GC7W+X83 Jl. Kuwung Mergelo Meri Kec. Magersari Kota Mojokerto Jawa Timur 61318',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Parkir','AC/Pemanas','Lobby Hotel','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Fleksibilitas Reservasi','Keamanan Aksesibilitas'],
            ],
            [
                'nama' => 'Grha Pawitra Trowulan',
                'harga' => 296100,
                'rating' => 4.9,
                'hotel_image_url' => 'Grha_Pawitra_Trowulan.jpg',
                'lokasi' => 'Jalan Candi Gentong Telogo Gede Brahu Kec. Trowulan Kabupaten Mojokerto Jawa Timur 61362',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Sarapan','Parkir','AC/Pemanas','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Fleksibilitas Reservasi','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Wisma & Kantin Amanda',
                'harga' => 200000,
                'rating' => 4.5,
                'hotel_image_url' => 'Wisma_&_Kantin_Amanda.jpg',
                'lokasi' => 'Jl. Air Panas No.20 Padusan Kec. Pacet Kabupaten Mojokerto Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Sarapan','Parkir','Lobby Hotel','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Pelatihan Staf','Akses ke Layanan Tambahan','Keamanan Aksesibilitas'],
            ],
            [
                'nama' => 'Royal Caravan Hotel & Outbound Trawas',
                'harga' => 425000,
                'rating' => 4.2,
                'hotel_image_url' => 'Royal_Caravan_Hotel_&_Outbound_Trawas.jpg',
                'lokasi' => 'Jl. Raya Trawas No.KM RW.17 Sukosari Kec. Trawas Kabupaten Mojokerto Jawa Timur 61375',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Sarapan','Parkir','AC/Pemanas','Playground','Lobby Hotel','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Akses ke Layanan Tambahan','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Airy Syariah Mojoanyar Mangga Satu Mojokerto',
                'harga' => 160000,
                'rating' => 4.4,
                'hotel_image_url' => 'Airy_Syariah_Mojoanyar_Mangga_Satu_Mojokerto.jpg',
                'lokasi' => 'Jl. Mangga Dusun Pasinan Desa No.1 Pasiman Jabon Kec. Mojoanyar Kota Mojokerto Jawa Timur 61364',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','AC/Pemanas','Lobby Hotel','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Kebersihan dan Perawatan Kamar','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Pelatihan Staf','Keamanan Aksesibilitas'],
            ],
            [
                'nama' => 'Nasta Inn Trawas',
                'harga' => 150000,
                'rating' => 4.9,
                'hotel_image_url' => 'Nasta_Inn_Trawas.jpg',
                'lokasi' => 'Jl. Raya Trawas No.417 Njuwok Ketapanrame Kec. Trawas Kabupaten Mojokerto Jawa Timur 61375',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','Playground','Lobby Hotel','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Pelatihan Staf','Akses ke Layanan Tambahan','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Arayanna hotel & resort',
                'harga' => 1462500,
                'rating' => 4.6,
                'hotel_image_url' => 'Arayanna_hotel_&_resort.jpg',
                'lokasi' => 'Trawas Jalan Udayana No.11 Kec. Trawas Kabupaten Mojokerto Jawa Timur 61375',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Sarapan','Parkir','AC/Pemanas','Playground','Lobby Hotel','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Akses ke Layanan Tambahan','Fleksibilitas Reservasi','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Fresh Green Hotel & Kebun Fresh Green',
                'harga' => 525000,
                'rating' => 3.9,
                'hotel_image_url' => 'Fresh_Green_Hotel_&_Kebun_Fresh_Green.jpg',
                'lokasi' => 'Dusun Bantal Desa RT.8/RW.2 Duyung Kec. Trawas Kabupaten Mojokerto Jawa Timur 61375',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Sarapan','Parkir','AC/Pemanas','Playground','Lobby Hotel','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Pelatihan Staf','Akses ke Layanan Tambahan','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Vila Jabal Rahmah Syariah',
                'harga' => 350000,
                'rating' => 4.4,
                'hotel_image_url' => 'Vila_Jabal_Rahmah_Syariah.jpg',
                'lokasi' => 'Kembang Kembangbelor Kec. Pacet Kabupaten Mojokerto Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','Playground','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Kebersihan dan Perawatan Kamar','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Akses ke Layanan Tambahan','Keamanan Aksesibilitas'],
            ],
            [
                'nama' => 'Villa Fanny Pacet ( Harus Satu Paket bundling )',
                'harga' => 3000000,
                'rating' => 4.2,
                'hotel_image_url' => 'Villa_Fanny_Pacet.jpg',
                'lokasi' => '8GGR+4H9 Jl. Kartini Made Pacet Kec. Pacet Kabupaten Mojokerto Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','Playground','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Kebersihan dan Perawatan Kamar','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi'],
            ],
            [
                'nama' => 'MJ HOTEL SYARIAH',
                'harga' => 348245,
                'rating' => 4.7,
                'hotel_image_url' => 'MJ_HOTEL_SYARIAH.jpg',
                'lokasi' => 'Jl. Brawijaya No.126 Wonogiri Tunggalpager Kec. Pungging Kabupaten Mojokerto Jawa Timur 61384',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Sarapan','Parkir','AC/Pemanas','Lobby Hotel','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Akses ke Layanan Tambahan','Keamanan Aksesibilitas','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Meriteduh Homestay ( /bulan bundling )',
                'harga' => 1200000,
                'rating' => 3.4,
                'hotel_image_url' => 'Meriteduh_Homestay.jpg',
                'lokasi' => 'Jl. Raya Meri No.372 Mergelo Meri Kec. Magersari Kota Mojokerto Jawa Timur 61315',
                'fasilitas' => ['Kamar','Kamar Mandi','Sarapan','Parkir','Televisi'],
                'kualitas_layanan' => ['Pelayanan Cepat dan Efisien','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik'],
            ],
            [
                'nama' => 'Raden Wijaya Hotel & Convention',
                'harga' => 405000,
                'rating' => 4.3,
                'hotel_image_url' => 'Raden_Wijaya_Hotel_&_Convention.jpg',
                'lokasi' => 'Jl. Raden Wijaya No.42 Mergelo Kranggan Kec. Prajurit Kulon Kota Mojokerto Jawa Timur 61321',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Sarapan','Parkir','AC/Pemanas','Lobby Hotel','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Akses ke Layanan Tambahan','Keamanan Aksesibilitas','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'VANDA Gardenia Hotel',
                'harga' => 479700,
                'rating' => 4.3,
                'hotel_image_url' => 'VANDA_Gardenia_Hotel.jpg',
                'lokasi' => 'Jl. Raya Trawas Slepi Ketapanrame Kec. Trawas Kabupaten Mojokerto Jawa Timur 60220',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Sarapan','Parkir','AC/Pemanas','Playground','Lobby Hotel','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Akses ke Layanan Tambahan','Fleksibilitas Reservasi','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Suwon homestay',
                'harga' => 352000,
                'rating' => 4.8,
                'hotel_image_url' => 'Suwon_homestay.jpg',
                'lokasi' => 'Suwon homestay Kali Jaten Selotapak Kec. Trawas Kabupaten Mojokerto Jawa Timur 61375',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Parkir','AC/Pemanas','Playground','Lobby Hotel','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Akses ke Layanan Tambahan','Keamanan Aksesibilitas','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Cangar Hotel - Swiss IND',
                'harga' => 120000,
                'rating' => 4.3,
                'hotel_image_url' => 'Cangar_Hotel_Swiss_IND.jpg',
                'lokasi' => 'Jl. Pacet sajen.38 Made Pacet Kec. Pacet Kabupaten Mojokerto Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Pelatihan Staf','Fleksibilitas Reservasi'],
            ],
            [
                'nama' => 'The Forest Onsen and Cafe',
                'harga' => 400000,
                'rating' => 4.3,
                'hotel_image_url' => 'The_Forest_Onsen_and_Cafe.jpg',
                'lokasi' => 'Jl. Air Panas, Padusan, Kec. Pacet, Kabupaten Mojokerto, Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Sarapan','Parkir','Playground','Lobby Hotel','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Pelatihan Staf','Fleksibilitas Reservasi','Keamanan Aksesibilitas','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Arca Cottages & Resort ( Bundle )',
                'harga' => 1800000,
                'rating' => 4.3,
                'hotel_image_url' => 'Arca_Cottages_&_Resort.jpeg',
                'lokasi' => 'Jl. Arca Medika, Jara am, Trawas, Kec. Trawas, Kabupaten Mojokerto, Jawa Timur 61375',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','AC/Pemanas','Lobby Hotel','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Keamanan Aksesibilitas'],
            ],
            [
                'nama' => 'Capital O 3359 Pondok Wisata Jaden',
                'harga' => 229855,
                'rating' => 1,
                'hotel_image_url' => 'Capital_O_3359_Pondok_Wisata_Jaden.jpeg',
                'lokasi' => 'Jl. Raya Slepi No.10, Slepi, Mojokerto, Kec. Trawas, Kabupaten Mojokerto, Jawa Timur 61375',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir'],
                'kualitas_layanan' => ['Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Informasi'],
            ],
            [
                'nama' => 'Villa Keeta ( bundling  )',
                'harga' => 5206307,
                'rating' => 5,
                'hotel_image_url' => 'Villa_Keeta.jpg',
                'lokasi' => 'Km 2, Soso, Cepokolimo, Pacet, Mojokerto Regency, East Java 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','Playground','Lobby Hotel','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Akses ke Layanan Tambahan','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Wildflower Trawas',
                'harga' => 1200000,
                'rating' => 4.6,
                'hotel_image_url' => 'Wildflower_Trawas.jpg',
                'lokasi' => 'Grand Trawas D - 82, Jibru, Belik, Kec. Trawas, Kabupaten Mojokerto, Jawa Timur 61375',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Duyung Trawas Hill Homestay',
                'harga' => 480000,
                'rating' => 4.5,
                'hotel_image_url' => 'Duyung_Trawas_Hill_Homestay.jpg',
                'lokasi' => '9J3C+Q3J, Dsn. Bantal, Duyung, Kec. Trawas, Kabupaten Mojokerto, Jawa Timur 61375',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Sarapan','Parkir','AC/Pemanas','Lobby Hotel','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Akses ke Layanan Tambahan','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Villa & Homestay Padi Park',
                'harga' => 225000,
                'rating' => 4.3,
                'hotel_image_url' => 'Villa_&_Homestay_Padi_Park.jpg',
                'lokasi' => 'Jl raya Pacet, Dusun Tameng, Padi, Kec. Gondang, Kabupaten Mojokerto, Jawa Timur 61372',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','AC/Pemanas','Playground','Televisi'],
                'kualitas_layanan' => ['Kebersihan dan Perawatan Kamar','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses ke Layanan Tambahan','Keamanan Aksesibilitas'],
            ],
            [
                'nama' => 'Villa Kangen Omah',
                'harga' => 510000,
                'rating' => 4.4,
                'hotel_image_url' => 'Villa_Kangen_Omah.jpg',
                'lokasi' => 'Jl. Pacet No.111, Kembang Sore, Petak, Kec. Pacet, Kabupaten Mojokerto, Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Parkir','AC/Pemanas','Lobby Hotel','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Akses ke Layanan Tambahan','Fleksibilitas Reservasi','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Villa de desa',
                'harga' => 1500000,
                'rating' => 4.5,
                'hotel_image_url' => 'Villa_de_desa.jpg',
                'lokasi' => 'Jl. Raya Pacet Trawas - Pacet KM 0, Pacet, Kec. Pacet, Kabupaten Mojokerto, Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Sarapan','Parkir','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Fleksibilitas Reservasi','Keamanan Aksesibilitas','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Villa Nabila',
                'harga' => 1200000,
                'rating' => 4.5,
                'hotel_image_url' => 'Villa_Nabila.jpeg',
                'lokasi' => 'Jl. Raya Pemandian Air Panas No.37, Padusan, Kec. Pacet, Kabupaten Mojokerto, Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','Playground','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Tanggapan Staf atas Keluhan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses ke Layanan Tambahan','Fleksibilitas Reservasi','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Villa Puncak Trawas',
                'harga' => 2500000,
                'rating' => 4.6,
                'hotel_image_url' => 'Villa_puncak_trawas.jpg',
                'lokasi' => 'Kemiloko, Trawas, Kec. Trawas, Kabupaten Mojokerto, Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Sarapan','Parkir','Playground','Lobby Hotel','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Pelatihan Staf','Akses ke Layanan Tambahan','Fleksibilitas Reservasi','Keamanan Aksesibilitas','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Villa Kebon Pakis (Bundling)',
                'harga' => 2000000,
                'rating' => 4.3,
                'hotel_image_url' => 'Villa_Kebon_Pakis.jpg',
                'lokasi' => 'Jl. Air Panas No.24, Padusan, Kec. Pacet, Kabupaten Mojokerto, Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Parkir','Playground','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Pelatihan Staf','Akses ke Layanan Tambahan','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Villa Kebon Pakis 2 (Bundling)',
                'harga' => 2000000,
                'rating' => 4.3,
                'hotel_image_url' => 'Villa_Kebun_Pakis_2_Pak_Sholeh.jpg',
                'lokasi' => 'Jl. Air Panas, Padusan, Kec. Pacet, Kabupaten Mojokerto, Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','Playground','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses ke Layanan Tambahan','Fleksibilitas Reservasi','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Villa Kebon Pakis 3 (Bundling)',
                'harga' => 2000000,
                'rating' => 4.3,
                'hotel_image_url' => 'Villa_Kebon_Pakis_3.jpg',
                'lokasi' => 'Jl. Pacet No.Km. 5, Made, Pacet, Kec. Pacet, Kabupaten Mojokerto, Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','Televisi'],
                'kualitas_layanan' => ['Kebersihan dan Perawatan Kamar','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Keamanan Aksesibilitas'],
            ],
            [
                'nama' => 'Villa Raisa',
                'harga' => 900000,
                'rating' => 4.2,
                'hotel_image_url' => 'Villa_Raisa.jpg',
                'lokasi' => 'Jl. Mojosari - Pacet No.31, Padusan, Kec. Pacet, Kabupaten Mojokerto, Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Kebersihan dan Perawatan Kamar','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Kerjasama Organisasi dan Asosiasi'],
            ],
            [
                'nama' => 'Homestay Nala',
                'harga' => 165000,
                'rating' => 4.1,
                'hotel_image_url' => 'Homestay_Nala.jpg',
                'lokasi' => 'Jl. Empunala No.295, Mergelo, Kedundung, Kec. Magersari, Kota Mojokerto, Jawa Timur 61316',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','AC/Pemanas','Televisi'],
                'kualitas_layanan' => ['Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Fleksibilitas Reservasi'],
            ],
            [
                'nama' => 'Villa Mediana Pacet',
                'harga' => 528000,
                'rating' => 4.4,
                'hotel_image_url' => 'Villa_Mediana_Pacet.jpeg',
                'lokasi' => '8GRP+7PW, Ledok, Pacet, Kec. Pacet, Kabupaten Mojokerto, Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Parkir','AC/Pemanas','Playground','Lobby Hotel','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Akses ke Layanan Tambahan','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => "Rere's House Villa",
                'harga' => 475000,
                'rating' => 4.5,
                'hotel_image_url' => 'Reres_House_Villa.jpg',
                'lokasi' => 'Jl. Air Terjun, Slepi, Ketapanrame, Kec. Trawas, Kabupaten Mojokerto, Jawa Timur 61375',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Fleksibilitas Reservasi'],
            ],
            [
                'nama' => 'Villa Panorama',
                'harga' => 3300000,
                'rating' => 4.9,
                'hotel_image_url' => 'Vila_PANORAMA.jpg',
                'lokasi' => 'Jl. Claket Inggil, Dusun Claket, Claket, Kec. Pacet, Kabupaten Mojokerto, Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','Playground','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses ke Layanan Tambahan','Fleksibilitas Reservasi','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Villa Pondok Nuansa',
                'harga' => 300000,
                'rating' => 4.3,
                'hotel_image_url' => 'Vila_Pondok_Nuansa.jpg',
                'lokasi' => 'Unnamed Road, Padusan, Pacet, Mojokerto Regency, East Java 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','Playground','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Akses ke Layanan Tambahan','Fleksibilitas Reservasi','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Hotel Slamet',
                'harga' => 331326,
                'rating' => 3.9,
                'hotel_image_url' => 'Hotel_Slamet.jpg',
                'lokasi' => 'Jalan Panglima Besar Sudirman No.51, Mergelo, Jagalan, Kec. Magersari, Kota Mojokerto, Jawa Timur 61313',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Sarapan','Parkir','AC/Pemanas','Playground','Lobby Hotel','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Fleksibilitas Reservasi','Keamanan Aksesibilitas'],
            ],
            [
                'nama' => 'The Alit Indonesia',
                'harga' => 651991,
                'rating' => 4.5,
                'hotel_image_url' => 'The_Alit_Indonesia.jpg',
                'lokasi' => 'Jl. Hasanudin, RT.04/RW.01, Sajen, Kec. Pacet, Kabupaten Mojokerto, Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Sarapan','Parkir','AC/Pemanas','Playground','Lobby Hotel','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Akses ke Layanan Tambahan','Fleksibilitas Reservasi','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Ayola Sunrise Mojokerto',
                'harga' => 450000,
                'rating' => 4.5,
                'hotel_image_url' => 'Ayola_Sunrise_Mojokerto.jpg',
                'lokasi' => 'Jl. Benteng Pancasila No.9, Mergelo, Balongsari, Kec. Magersari, Kota Mojokerto, Jawa Timur 61314',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Sarapan','Parkir','AC/Pemanas','Playground','Lobby Hotel','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Akses ke Layanan Tambahan','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'SUWON CAMP',
                'harga' => 451200,
                'rating' => 4.5,
                'hotel_image_url' => 'SUWON_CAMP.jpg',
                'lokasi' => 'Jl. Tamiajeng, Tamiajeng, Kec. Trawas, Kabupaten Mojokerto, Jawa Timur 61375',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','Playground','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Akses ke Layanan Tambahan','Fleksibilitas Reservasi','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'THE PEKAYON VILLA PACET',
                'harga' => 2072778,
                'rating' => 4.8,
                'hotel_image_url' => 'THE_PEKAYON_VILLA_PACET.jpg',
                'lokasi' => 'Jl. Motruno, Nono, Kemiri, Kec. Pacet, Kabupaten Mojokerto, Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Parkir','AC/Pemanas','Playground','Lobby Hotel','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses ke Layanan Tambahan','Fleksibilitas Reservasi','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'The Soemo Hills',
                'harga' => 1218000,
                'rating' => 4.5,
                'hotel_image_url' => 'The_Soemo_Hills.jpg',
                'lokasi' => 'Hutan, Padusan, Kec. Pacet, Kabupaten Mojokerto, Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Sarapan','Parkir','AC/Pemanas','Playground','Lobby Hotel','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Akses ke Layanan Tambahan','Fleksibilitas Reservasi','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
            [
                'nama' => 'Villa SB',
                'harga' => 3622422,
                'rating' => 4.9,
                'hotel_image_url' => 'Villa_SB.jpg',
                'lokasi' => 'Nono Ds, Jl. Motruno, Mrasih, Kemiri, Kec. Pacet, Kabupaten Mojokerto, Jawa Timur 61374',
                'fasilitas' => ['Kamar','Kamar Mandi','Akses Internet','Sarapan','Parkir','Playground','Lobby Hotel','Ruangan Fungsional','Televisi'],
                'kualitas_layanan' => ['Keramahan Staf','Pelayanan Cepat dan Efisien','Kebersihan dan Perawatan Kamar','Tanggapan Staf atas Keluhan','Personalisasi Layanan','Keamanan Pelanggan'],
                'kemudahan_aksesibilitas' => ['Akses Fisik','Akses Informasi','Pelatihan Staf','Akses ke Layanan Tambahan','Fleksibilitas Reservasi','Keamanan Aksesibilitas','Kerjasama Organisasi dan Asosiasi','Komunikasi yang Efektif'],
            ],
        ];

        foreach ($hotels as $hotelData) {
            Hotel::create([
                'nama' => $hotelData['nama'],
                'harga' => $hotelData['harga'],
                'rating' => $hotelData['rating'],
                'hotel_image_url' => $hotelData['hotel_image_url'],
                'lokasi' => $hotelData['lokasi'],
                'kualitas_layanan' => json_encode($hotelData['kualitas_layanan']),
                'fasilitas' => json_encode($hotelData['fasilitas']),
                'kemudahan_aksesibilitas' => json_encode($hotelData['kemudahan_aksesibilitas']),
            ]);
        }
    }
}
